library(sidescroller)
library(here)

template <- sidescroller() %>%
  #Title Slide
  title_slide(
    title = "{sidescroller}",
    subtitle = c("Tell the Story"),
    text_align = "center"
  ) %>%

  #Introduction
  slide_markdown(
    title = "Introduction to {sidescroller}","
    sidescroller comes from the idea that presentations are meant to be stories.
    
    Most presentation tools that exist are now a crutch that allows the user to throw up some text and images on a slide with no connection to the flow of the story.

    By assembling your presentation as a series of connected panels you are able to create a rich story.

    To get started, begin by installing {sidescroller} from github:

    ```r
    # install.packages(\"remotes\")
    remotes::install_github(\"thebioengineer/sidescroller\")
    ```
    ",style = "width:1000px") %>%

  # Initializing {sidescroller}
  slide_markdown(
    title = "Starting your {sidescroller}","
    After installing {sidescroller}, open a new r script file to begin, and load the namespace.

    ```r
    library(sidescroller)

    ```

    The first Step to creating a presentation is to use `sidescroller()` and assign it to an object.

    ```r
    pres <- sidescroller()
    ```
    ") %>%


  #### Slides
  slide_multipanel(
    title = "Slides in sidescroller",
    panel_markdown("
    - To build up your presentation, use the family of _slide_ functions that come natively built into the package.

    - The list of available functions for creating your slides are as follow:
        - slide
        - title_slide
        - slide_markdown
        - slide_wide
        - slide_wide_markdown
        - slide_multipanel



    - The `slide_*` functions are wrappers around the `slide()` function that are opinionated and designed to facilitate the generation of presentations with the least friction.
    
    - For example, the slides we are currently going through are an example of using `slide_multipanel()`.
    ",style = "width: 600px"),

    #### title slide
    panel_markdown("
    ### title_slide

    - `title_slide()` is for creating the title slide of the presentation, or for separating and creating 'chapters' in the slides.
    - These slides are the full width of the presentation window.

    - There can be a number of subtitles passed through the `subtitle` argument, each subtitle is an entry in a character vector.
    ",style = "width: 600px"),

    #### slide
    panel_markdown("
    ### slide and slide_markdown

    - `slide()` is the least opinionated function to use when generating a slide.
        - Slide contents are provided as html tags.
        - `htmltools` package is loaded to the namespace to provide the necessary tools for creating the html from within an R script.


    - `slide_markdown()` is for creating the slide contents by writing in markdown to get around needing to have knowledge of html.
        - Since most `R` users are comfortable writing markdown from the `rmarkdown` and `xaringan` packages, this is a natural way to make slide creation.
        - Contents can be interpreted as an rmarkdown document and thus will try to render supplied code within the code chunks.
    ",style = "width: 600px"),

    #### slide wide
    panel_markdown("
    ### slide_wide and slide_wide_markdown

    - `slide_wide()` and  `slide_wide_markdown()` are for creating slides that are the full width of the presentation window.

    - This is *MOST* similar to the current presentation format that most other slide presentations take.

    - Similarly to `slide()` and `slide_markdown()`, the `slide_wide()` function uses html tags to create content, and `slide_wide_markdown()` uses markdown.
    ",style = "width: 600px"),

    #### slide multipanel
    panel_markdown("
    ### slide_multipanel

    - `slide_multipanel()` is the most unique aspect of {slidescroller}, in that it can have progressive contents.

    - The contents of this slide is built from either `panel()` or `panel_markdown()` functions.

    - They help simulate the idea of stories by having a single title for a series of panels that progressively appear.

    - Like the other variants of functions, `panel()` accepts html tags, and `panel_markdown()` uses markdown syntax to generate content.
    ",style = "width: 600px"),
    style="background-color: #d7d8d2;") %>%

  ####  Piping
  slide_multipanel(
    title = "Making the Presentation with {sidescroller}",
    panel_markdown("
    Each of the `slide` functions first argument is the object generated by the `sidescroller()` function.
    This tells {sidescroller} to append the slide onto the presentation, so order matters.
    The output of each `slide` function is then an updated `sidescroller` object with the new slide.

    Using base R, you could then follow the pattern:

    ```r
    pres <- sidescroller()
    pres <- title_slide(pres,title = \"Presentation Title\",subtitle = \"Amazing Subtitle\")
    pres <- slide_markdown(pres,title = \"Slide 1\", content = \"Slide Content\")
    ```
    ",style = "width: 600px"
    ),
    panel_markdown("
    However, {sidescroller} has the `magrittr` pipe function exported, so we can simpify the process:

    ```r
    pres <- sidescroller() %>%
               title_slide(pres,
                   title = \"Presentation Title\",
                   subtitle = \"Amazing Subtitle\") %>%
               slide_markdown(pres,
                   title = \"Slide 1\",
                   content = \"Slide Content\")
    ```
    ", style = "width: 700px")
  ) %>%
  
  slide_markdown(
    title = "Saving the presentation","
    In order to save the presenation, use `save_sidescroller()`, which is a wrapper around `save_html()` from `htmltools`.
    
    ```r
    save_sidescroller(pres,\"my_presentation.html\")
    
    ```
    
    Now, to view your new presentation, you can either double click on the newly generated HTML file.
    
    Alternately, using RStudio, you can view your presentation in the viewer:
    
    ```
    rstudioapi::viewer(\"my_presentation.html\")
    ```
    
    ",  style = "background-color: #d7d8d2;width:900px") %>% 
  
  slide_markdown(
    title = "R and Markdown",
    "
    Rmarkdown syntax can be used!
    
    For example, below I will generate a plot using the following code:
    
    ```{r}
    
    plot(mtcars$disp,mtcars$mpg)
    ```
    
    "
  ) %>% 
  
  slide_markdown(
    title = "Widgets",
    markdown_to_html("
    HTML Widgets are not currently supported when they are content of markdown. 
    Their HTML needs to be configured to operate properly.
    
    At this moment, if you wanted a leaflet like below to show up: 
    ```r
    library(leaflet)
    leaflet() %>% addTiles() %>% setView(-93.65, 42.0285, zoom = 17)
    ```
    The code would need to live as an entry to the slide like below.
    
    ```r
    slide(
      title=\"Check out this map!\",
      leaflet() %>% addTiles() %>% setView(-93.65, 42.0285, zoom = 17)
    )
    ```
    The next slide is what that code looks like rendered.
    ")) %>%
  
  slide(
    title = "Check out this map!",
    leaflet::leaflet() %>% leaflet::addTiles() %>% leaflet::setView(-93.65, 42.0285, zoom = 17),
    style = "width:1000px"
    ) %>%  
  
  ####  Secret sauce
  slide_wide_markdown(
    title = "Secret Sauce","
    The power of {sidescroller} comes from [slick.js](http://kenwheeler.github.io/slick) by [Ken Wheeler](https://kenwheeler.github.io) combined with some custom jquery and css code.

    Many thanks to Ken for developing the image carousel library and making it so flexible.
    ",  style = "background-color: #d7d8d2;") %>% 
  
  slide_wide(
    title = NULL,
    markdown_to_html("# Thank you for your consideration and review of this project
    
    
    Please refer any suggestions you have to the github repo:
    
    [here](https://www.github.com/thebioengineer/sidescroller)
    "),
    div(
      img(src = "www/scroll.webp",
        style = "width: 59%;position: relative;max-height: 300px;margin: auto;"),
      p("https://publicdomainvectors.org/photos/Scroll5.png",style = "font-size:10px")
    ),
    style = "text-align: center;"
  )
  

save_sidescroller(template,
                  here::here("docs/index.html"))
