
#' @title Side Scroller Initializer
#' Initialize a Side Scroller
#' @description  initialize a side scroller object
#' @param html_dependencies list of html dependencies, generated by `htmltools::htmlDependency`.
#' @import htmltools
#' @export
#' @examples
#' x <- sidescroller()
#' 
#' ## Add font-awesome dependency
#' x <- sidescroller(
#'          list(htmltools::htmlDependency(
#'             name = "font-awesome",
#'             version = "4.7.0",
#'             src = c(href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/"),
#'             stylesheet = "font-awesome.min.css")
#'          )))
#' 
sidescroller <- function(html_dependencies=NULL){
  
  stopifnot(is.null(html_dependencies) | is.list(html_dependencies))
  
  slide_master <- div(class = "slide_master_wrapper",div(class = "slide_master"))

  slide_master <- htmltools::attachDependencies(
    slide_master, c(sidescrollDependencies(),html_dependencies)
  )

  class(slide_master) <- c(class(slide_master),"sidescroller")
  
  slide_master
}


#' Check if is a side scroller object
#' @param x object to be checked if it is a side scroller
#' @export
#' @examples
#' x <- sidescroller()
#' is_sidescroller(x)
is_sidescroller <- function(x){
  "sidescroller" %in% class(x)
}




